# Generated by Django 5.0.6 on 2024-09-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="device_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="process_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
