# Generated by Django 5.0.6 on 2024-09-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_account_refresh_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="process_day",
        ),
        migrations.AddField(
            model_name="account",
            name="status",
            field=models.CharField(default="standby", max_length=255),
        ),
        migrations.AlterField(
            model_name="account",
            name="progress",
            field=models.IntegerField(default=1),
        ),
    ]
