# Generated by Django 5.0.6 on 2024-10-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_remove_account_process_day_account_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
