# Generated by Django 5.0.6 on 2024-10-14 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_title'),
        ('modeles', '0002_modeles_description'),
        ('strategies', '0004_alter_strategy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='modele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modeles.modeles'),
        ),
        migrations.AlterField(
            model_name='account',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='strategies.strategy'),
        ),
    ]
