# Generated by Django 5.0.6 on 2024-10-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_account_modele_alter_account_strategy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="strategy",
        ),
        migrations.AddField(
            model_name="account",
            name="insta_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
