# Generated by Django 5.0.6 on 2024-11-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_remove_account_strategy_account_insta_username_and_more"),
        ("strategies", "0006_alter_strategy_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="strategies.strategy",
            ),
        ),
    ]
