# Generated by Django 5.0.6 on 2024-11-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_account_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="distance",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="account",
            name="max_age",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="account",
            name="min_age",
            field=models.IntegerField(default=18),
        ),
    ]
