# Generated by Django 5.0.6 on 2025-01-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_account_distance_account_max_age_account_min_age"),
    ]

    operations = [

        migrations.AlterField(
            model_name="account",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
