# Generated by Django 5.0.6 on 2024-11-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="isActive",
            field=models.BooleanField(default=False),
        ),
    ]
