# Generated by Django 5.0.6 on 2024-11-18 23:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_isactive"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="isActive",
            new_name="is_active",
        ),
    ]
