# Generated by Django 5.0.6 on 2024-09-24 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxies", "0001_initial"),
        ("strategies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="proxy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="proxies.proxy",
            ),
        ),
    ]
