# Generated by Django 5.0.6 on 2024-09-25 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxies", "0002_proxy_name"),
        ("strategies", "0002_strategy_proxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="proxy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="proxies.proxy",
            ),
        ),
    ]
