# Generated by Django 5.0.6 on 2024-10-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0003_alter_strategy_proxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
