# Generated by Django 5.0.6 on 2024-10-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0004_alter_strategy_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
