# Generated by Django 5.0.6 on 2024-11-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0005_alter_strategy_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
