# Generated by Django 5.0.6 on 2024-09-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxy",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
