# Generated by Django 5.0.6 on 2024-10-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0002_proxy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
