# Generated by Django 5.0.6 on 2024-09-23 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proxies", "0001_initial"),
        ("strategies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("bot_name", models.CharField(max_length=255, unique=True)),
                ("min_swipe_times", models.IntegerField(default=0)),
                ("max_swipe_times", models.IntegerField(default=100)),
                ("min_right_swipe_percentage", models.FloatField(default=0.5)),
                ("max_right_swipe_percentage", models.FloatField(default=0.5)),
                ("device_id", models.CharField(max_length=255)),
                ("status", models.CharField(default="Stopped", max_length=20)),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                ("scheduled_time_2", models.TimeField(blank=True, null=True)),
                ("related_day", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proxy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="proxies.proxy",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategies.strategy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
