# Generated by Django 5.0.6 on 2024-09-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botsettings",
            name="device_id",
        ),
    ]
