# Generated by Django 5.0.6 on 2024-09-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_remove_botsettings_device_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botsettings",
            name="proxy",
        ),
    ]
