# Generated by Django 5.0.6 on 2024-09-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_remove_botsettings_proxy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botsettings",
            name="bot_name",
        ),
    ]
